name: 'Component Nomad Job File Parser'
description: 'Parses Nomad job files from MFDLABS Components v4'
author: 'MFDLABS'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: arrow-up
  color: gray-dark

# Define your inputs here.
inputs:
  components:
    description: 'The list of paths to the components'
    required: true

  datacenters:
    description: 'The list of data centers'
    required: false
    default: '*'

# Define your outputs here.
outputs:
  nomad-files:
    description: 'Key value pairs of the component name and the nomad job file'

runs:
  using: node20
  main: dist/index.js
